/*FIRST*/
CREATE OR REPLACE FUNCTION TEN_PRODUCTS_COUNTER
    RETURN INT
    AS
        TEN_PRODUCTS_VALUE INT;
    BEGIN
    /*NO LOGIC IN THE NEXT STRING*/
        SELECT COUNT (*) INTO TEN_PRODUCTS_VALUE FROM ORDERS WHERE ORDERITEMS.QUANTITY = 10;
        RETURN TEN_PRODUCTS_VALUE;
    END TEN_PRODUCTS_COUNTER;

/*SECOND*/
SET SERVEROUTPUT ON;
/*
DECLARE
    names_of_non_buyer char(10);
*/
DECLARE
    name_of_non_buyer char(30);
    
CREATE OR REPLACE PROCEDURE NON_PRODUCTED

IS 
BEGIN

SELECT VENDORS.VEND_NAME INTO name_of_non_buyer FROM VENDORS WHERE PRODUCTS.PROD_ID != VENDORS.PROD_ID; 

EXCEPTION 
    DBMS_OUTPUT.PUT_LINE('EXCEPTION');
END NON_PRODUCTED;

/*THIRD*/
CREATE OR REPLACE PROCEDURE GARBADGE_COLLECTOR()
IS 
BEGIN

END GARBADGE_COLLECTOR;
