-- LABORATORY WORK 5
-- BY Moroziuk_Yevhenii
SET SERVER OUTPUT;

-- 1

CREATE OR REPLACE FUNCTION count_of_product
(
  order_num ORDERS.ORDER_NUM%TYPE
) RETURN INTEGER
IS count_of_products INTEGER;
  BEGIN
    SELECT COUNT( DISTINCT PRODUCTS) INTO count_of_products
    FROM ORDERS 
    JOIN ORDERITEMS ON
      ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
    JOIN PRODUCTS ON
      ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID
    WHERE ORDERS.ORDES_NUM = order_num;
  END count_of_product;
  
-- 2

CREATE OR REPLACE PROCEDURE proced
(
  prod_name IN PRODUCTS.PROD_ID%TYPE,
  vend_iNFO OUT VEND_INF%TYPE
) IS 
BEGIN
  SELECT 
    TRIM(VENDORS.VEND_ID)||TRIM(VENDORS.VEND_NAME) INTO vend_INFO
  FROM VENDORS JOIN PRODUCTS ON
    VENDORS.VEND_ID = PRODUCTS.PROD_ID
  WHERE PRODUCTS.PROD_NAME = prod_name;
EXCEPTION NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE('ERROR!')
END proced;

-- 3

CREATE OR REPLACE PROCEDURE proced_2 
(
    prod_name IN PRODUCTS.PROD_ID%TYPE
) IS
BEGIN
  IF prod_name IN PRODUCTS THEN 
    EXCEPTION  DBMS_OUTPUT.PUT_LINE('ERROR!')
  ELSE INSERT INTO PRODUCTS (PROD_ID, VEND_ID, PROD_NAME, PROD_PRICE) VALUES (1,1,prod_name, 1) 
END proced_2;










