-- LABORATORY WORK 2
-- BY Kovalchuk_Yuliia
/*---------------------------------------------------------------------------
1. Вивести ключ продукту та ключ його постачальника, за умови, що даний продукт продавався у трьох замовленнях, загальна вартість кожного зних більша 500.

---------------------------------------------------------------------------*/
--Код відповідь:
SELECT
    VENDORS.VENDS_ID
    PRODUCTS.PRODS_ID
FROM
(SELECT
VENDORS.VEND_ID
 PRODUCTS.PROD_ID
SUM(ORDERITEMS.OUANTITY*ORDERITEMS.ITEM_PRICE) AS SUM_ORDER
FROM
CUSTUMERS JOIN ORDERS 
ON CUSTUMERS.CUST_ID=ORDERS.CUST_ID
JOIN ORDERITEMS
ON ORDERS.ORDER_NAM=ORDERITEMS.ORDER_NAM
JOIN PRODUCTS
ON ORDERITEMS.PROD_ID=PRODUCTS.PROD_ID
JOIN VENDORS
ON PRODUCTS.VEND_ID=VENDORS.VEND_ID
GROUP BY VENDORS.VEND_ID
 PRODUCTS.PROD_ID
HAVING CUSTOMER.SUM_ORDER>=500 AS PRODS_ID
)
(SELECT VENDORS.PROD_ID
ORDERITEMS.PROD_ID
FROM 
ORDERITEMS JOIN PRODUCTS
ON ORDERITEMS.PROD_ID=PRODUCTS.PROD_ID
JOIN VENDORS
ON PRODUCTS.VEND_ID=VENDORS.VEND_ID
GROUP BY VENDORS.PRODS_ID
ORDERITEMS.PRODS_ID
HAVING COUNT(DESCRIBE PRODUCT.PROD_ID)=3 AS VENDS_ID
);

 
/* --------------------------------------------------------------------------- 
2.  Вивести назви країн та вказати, скільки в ній живе постачальників і скільки покупців продуктів цих постачальників.

---------------------------------------------------------------------------*/
--Код відповідь:

    SELECT
    CUSTUMERS.CUST_COUNTRY
    COUNT(VENDORS.VAND_NAME)
    
    FROM  
    (SELECT VENDORS.PROD_ID
ORDERITEMS.PROD_ID
FROM 
ORDERITEMS JOIN PRODUCTS
ON ORDERITEMS.PROD_ID=PRODUCTS.PROD_ID
JOIN VENDORS
ON PRODUCTS.VEND_ID=VENDORS.VEND_ID
GROUP BY VENDORS.PRODS_ID
ORDERITEMS.PRODS_ID
  )
  CUSTUMERS.CUST_ID
CUSTUMERS JOIN ORDERS 
ON CUSTUMERS.CUST_ID=ORDERS.CUST_ID
JOIN ORDERITEMS
ON ORDERS.ORDER_NAM=ORDERITEMS.ORDER_NAM
JOIN PRODUCTS
ON ORDERITEMS.PROD_ID=PRODUCTS.PROD_ID
JOIN VENDORS
ON PRODUCTS.VEND_ID=VENDORS.VEND_ID
GROUP BY VENDORS.COUNTRU_ID
 VENDORS.VAND_NAME
 );
 
 










