-- LABORATORY WORK 4
-- BY Hrydko_Oleksandr
/*трігер
При зміні країни видаляються всі будинки,що знаходяться в країні.*/
CREATE OR REPLACE TRIGGER DELETE_
BEFORE UPDATE OF COUNTRY ON STREET
FOR EACH ROW
DECLARE
STREET_NAME_ STREET.STREET_NAME%TYPE;
STREET_NUMBER_ STREET.STREET_NUMBER%TYPE;
BEGIN 
STREET_NAME_:=:OLD.STREET.STREET_NAME;
STREET_NUMBER_:=:OLD.STREET.STREET_number;
DELETE 
FROM STREET_ON_HOUSE
WHERE STREET_NAME_= STREET_ON_HOUSE.STREET_NAME AND  STREET_NUMBER_= STREET_ON_HOUSE.STREET_NUMBER;
END;

/*трігер 
При додаванні людини його автоматично селять у будинок.*/
CREATE OR REPLACE TRIGGER INSERT_
BEFORE INSERT  ON PEOPLE
FOR EACH ROW
DECLARE
PEOPLE_ID_ PEOPLE.PEOPLE_ID%TYPE;
HOUSE_NUMBER_ HOUSE.HOUSE_NUMBER%TYPE;
HOUSE_AREA_ HOUSE.HOUSE_AREA%TYPE;
COUNT_OF_PEOPLE_ HOUSE.COUNT_OF_PEOPLE%TYPE;
BEGIN 
PEOPLE_ID_ := :NEW.PEOPLE.PEOPLE_ID;
HOUSE_NUMBER_ :=4;
HOUSE_AREA_:=50;
COUNT_OF_PEOPLE_:=1;
INSERT INTO HOUSE 
VALUES(HOUSE_NUMBER_,PEOPLE_ID_,HOUSE_AREA_,COUNT_OF_PEOPLE_);
END INSERT_;

/*курсор з параметром назва вулиці
вивести всіх людей,що живуть на цій вулиці.*/
DECLARE 
PEOPLE_ID_ HOUSE.PEOPLE_ID%TYPE;
CURSOR PEOPLE_(STREET_NAME_ STREET.STREET_NAME%TYPE)
IS 
SELECT HOUSE.PEOPLE_ID AS P
FROM STREET JOIN STREET_ON_HOUSE 
ON STREET.STREET_NAME=STREET_ON_HOUSE.STREET_NAME
JOIN HOUSE ON 
STREET_ON_HOUSE.HOUSE_NUMBER = HOUSE.HOUSE_NUMBER 
WHERE STREET.STREET_NAME = STREET_NAME_ ;

BEGIN


FOR REC IN PEOPLE_('VASULKIVSKA')LOOP
DBMS_OUTPUT.PUT_LINE(REC.P);
END LOOP;

END;



