-- LABORATORY WORK 5
-- BY Khodakivskyi_Vadym
--Написати функцію, що повертає назву найдорожчого продукту у замовленні, за ключем замовлення
CREATE OR REPLACE FUNCTION EXP_PROD (ORDER_KEY IN NUMBER,NAME_PR OUT VARCHAR2) RETURN VARCHAR2 
 IS
 BEGIN
    SELECT PRODUCTS.PROD_NAME INTO NAME_PR
    FROM orders JOIN ORDERITEMS
    ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
    JOIN PRODUCTS ON products.prod_id = ORDERITEMS.PROD_ID
    WHERE ORDERS.ORDER_NUM = ORDER_KEY AND
    ITEM_PRICE = (SELECT MAX(ORDERITEMS.ITEM_PRICE)
    FROM ORDERITEMS.ITEM_PRICE);
  RETURN (NAME_PR);
END EXP_PROD;

-- Написати процедуру, що за назвою продукту повертає ім'я його постачальника, якщо операція не можлива процедура кидає exception
CREATE OR REPLACE PROCEDURE VEND_NAME (NAME_PROD IN VARCHAR2, VEND_NAME OUT VARCHAR2) AS
BEGIN
 SELECT VENDORS.VEND_NAME INTO VEND_NAME
 FROM VENDORS JOIN PRODUCTS ON VENDORS.VEND_ID = products.prod_id
 WHERE PRODUCTS.PROD_NAME = name_prod;
EXCEPTION 
 WHEN NO_DATA_FOUND THEN
  dbms_output.put_line("BIDA");
END VEND_NAME;

--написати процедуру, що додає новий продукт постачальнику.....
CREATE OR REPLACE PROCEDURE INS_PROD (VENDOR_ID IN VARCHAR2, PID IN VARCHAR2, PNAME IN VARCHAR2, PRICE IN NUMBER) AS
BEGIN
INSERT INTO PRODUCTS (PROD_ID, VEND_ID, PROD_NAME, PROD_PRICE) 
VALUES (PID,VENDOR_ID,PNAME,PRICE);
EXCEPTION 
WHEN NO_DATA_FOUND THEN 
dbms_output.put_line("NE ZNAYDENO");
END INS_PROD;
