-- LABORATORY WORK 5
-- BY Kupar_Kristina
CREATE OR REPLACE FUNCTION count_of_orders(
  customer_id orders.cust_id%TYPE)
  RETURN orders_count AS orders_count INT;
IS
  BEGIN
  SELECT COUNT(ORDER_ITEM) INTO  ORDERS_COUNT FROM (ORDERS JOIN ORDERITEMS ON ORDERITEMS.ORDER_NUM = ORDERS.ORDER_NUM)
  IF ORDERS_COUNT > 1
  THEN ORDERS_COUNT = 0
  RETURN ORDERS_COUNT
END COUNT_OF_ORDERS;




CREATE OR REPLACE PROCEDURE COUNT_OF_CUST(
  PRODUCT_NAME IN PRODUCTS.PROD_NAME%TYPE)
AS
  BEGIN
