-- LABORATORY WORK 5
-- BY Pidhainyi_Anton
CREATE OR REPLACE FUNCTION count_prod(ord_num ORDERITEMS.ORDER_NUM%TYPE)
return INTEGER
AS
  sum_result INTEGER;  
BEGIN
  SELECT SUM(QUANTITY) INTO sum_result FROM ORDERITEMS WHERE ORDER_NUM=ord_num;
  return sum_result;  
END count_prod;

CREATE OR REPLACE PROCEDURE get_key_name(pr_name IN PRODUCTS.PROD_NAME%TYPE,
  custID OUT CUSTOMERS.CUST_ID%TYPE, custName OUT CUSTOMERS.CUST_NAME%TYPE)
IS
BEGIN
  SELECT CUSTOMERS.CUST_ID INTO custID, CUSTOMERS.CUST_NAME INTO custName FROM (PRODUCTS JOIN ORDERITEMS ON ORDERITEMS.PROD_ID=PRODUCTS.PROD_ID
    JOIN ORDERS ON ORDERS.ORDER_NUM=ORDERITEMS.ORDER_NUM
      JOIN CUSTOMERS ON CUSTOMERS.CUST_ID=ORDERS.CUST_ID)
        WHERE PROD_NAME=pr_name;
  EXCEPTION WHEN data_no_found
    dbms_output.putline("data no found");
  EXCEPTION WHEN other
    dbms_output.putline("error");
END get_key_name;

