CREATE TABLE DISCIPLINE (
  DISCIPLINE_NAME VARCHAR2(30),
  CONSTRAINT PK_DISCIPLINE PRIMARY KEY (DISCIPLINE_NAME)
);

CREATE TABLE HOMEWORK (
  DISCIPLINE VARCHAR2(30),
  HOMEWORK_DATE DATE NOT NULL,
  DESCRIPTION VARCHAR2(300),
  CONSTRAINT PK_HOMEWORK PRIMARY KEY (DISCIPLINE, HOMEWORK_DATE)
);

ALTER TABLE HOMEWORK ADD CONSTRAINT FK_HOMEWORK__DISCIPLINE
FOREIGN KEY (DISCIPLINE) REFERENCES DISCIPLINE (DISCIPLINE_NAME);

CREATE TABLE USERS (
  PASS_ID VARCHAR2(8),
  USER_NAME VARCHAR2(30),
  UNI_ROLE VARCHAR2(30),
  CONSTRAINT PK_USER PRIMARY KEY (PASS_ID)
);

CREATE TABLE MARK (
  USER_NAME VARCHAR2(30),
  DISCIPLINE VARCHAR2(30),
  MARK NUMBER,
  CONSTRAINT PK_MARK PRIMARY KEY (DISCIPLINE, USER_NAME)
);

ALTER TABLE MARK ADD CONSTRAINT FK_MARK__DISCIPLINE 
FOREIGN KEY (DISCIPLINE) REFERENCES DISCIPLINE (DISCIPLINE_NAME);

ALTER TABLE USERS
ADD CONSTRAINT ROLE_CHECK CHECK (UNI_ROLE IN ('STUDENT', 'TEACHER'));

ALTER TABLE MARK
ADD CONSTRAINT MARK_CHECK CHECK (MARK BETWEEN 0 AND 100);
