-- LABORATORY WORK 3
-- BY Miliev_Maksym
 -- LABORATORY WORK 3
 -- BY Miliev_Maksym
+--1
+DECLARE VENDORID VENDORS.VEND_ID%TYPE
+        VENDORNAME VENDORS.VEND_NAME%TYPE
+        ORDERITEMTYPE VARCHAR(15)
+        BEGIN
+    VENDORS.VEND_ID = 'BRS01'
+    SELECT VENDORS.VEND_ID, 
+    --2
+    DECLARE V_CUST_ID
+
+STATUS VARCHAR2(12):= ' ';
+VEND VENDORS.VEND_ID%TYPE;
+COUNS INTEGER;
+
+BEGIN
+SELECT VENDORS.VEND_ID, COUNT(PRODUCTS.PROD_ID)
+FROM VENDORS LEFT JOIN PRODUCTS
+ON VENDORS.VEND_ID = PRODUCTS.VEND_ID
+GROUP BY VENDORS.VEND_ID
+HAVING VENDORS.VEND_ID = VEND;
+IF COUNS = 2 
+THEN STATUS = 'YES'
+IF COUNS > 2
+THEN STATUS = 'NO'
+ELSE STATUS = 'unknown'
+END IF
+END;
+--3
+CREATE VIEW PRODUCT_CUSTOMER AS
+SELECT
+    PRODUCTS.PROD_NAME,
+    CUSTOMERS.CUST_COUNTRY,
+    ORDERS.ORDER_NUM
+    
+    FROM PRODUCTS JOIN ORDERITEMS
+    ON PRODUCTS.PROD_ID = ORDERITEMS.PROD_ID
+    
+    JOIN ORDERS ON
+    ORDERITEMS.ORDER_NUM = ORDERS.ORDER_NUM
+    
+    JOIN CUSTOMERS ON ORDERS.CUST_ID = CUSTOMERS.CUST_ID
+    SELECT COUNT(PROD_NAME)
+    FROM PRODUCT_CUSTOMER
+    WHERE CUST_COUNTRY = 'Gernamy';
+    SELECT PROD_NAME,
+    COUNT (DISTINCT(ORDER_NUM))
+    FROM PRODUCT_CUSTOMER
+    GROUP BY PROD_NAME;
+    
