-- LABORATORY WORK 2
-- BY Miliev_Maksym
----1
SELECT DISTINCT
    PRODUCTS.PROD_NAME
    FROM 
    CUSTOMERS JOIN ORDERS
        ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID 
        JOIN ORDERITEMS
        ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
        JOIN ORDERITEMS
        ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
        JOIN PRODUCTS 
        ON ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID
        JOIN VENDORS 
        ON PRODUCTS.VEND_ID = VENDORS.VEND_ID
        WHERE 
        ORDERITEMS.PROD_ID IN(
        
        SELECT
            ORDERITEMS.PROD_ID
                FROM 
                ORDERITEMS
                    GROUP BY ORDERITEMS.PROD_ID
                    HAVING SUM (ORDERITEMS.QUANTITY) IN (
                    
                    SELECT
                    MAX(PROD_QUANTITY)
                    FROM
                    (

    SELECT 
        ORDERITEMS.PROD_ID, SUM(ORDERITEMS.QUANTITY)
        FROM ORDERITEMS
        GROUP BY ORDERITEMS.PROD_ID)));
  ----2      
        SELECT MAX (CUSTOMERS_COUNT)
FROM(
SELECT VENDORS.VEND_ID, COUNT (CUSTOMERS.CUST_ID) AS CUSTOMERS_COUNT
FROM CUSTOMERS JOIN ORDERS 
ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
JOIN ORDERITEMS
ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
JOIN PRODUCTS
ON ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID
JOIN VENDORS
ON PRODUCTS.VEND_ID = VENDORS.VEND_ID
GROUP BY VENDORS.VEND_ID);
