/*1 завдання*/
create function sess(IN i INT, OUT SS INT)
BEGIN
  SELECT COUNT(QUANTITY) INTO SS FROM ORDERITEMS
  JOIN ORDERS AS  ORDERITEMS.ORDER_NUM = ORDERS.ORDER_NUM
  JOIN CUSTOMERS AS ORDERS.CUST_ID = i
  WHERE COUNT(QUANTITY) >= 10;
RETURN SS
END
 
/*2 завдання*/
CREATE PROCEDURE SERGO(prod STRING)
BEGIN
  IF(prod in select prod_name from products)

    SELECT COUNT(CUST_NAME) FROM CUSTOMERS
    JOIN ORDEITEMS AS PRODUCTS.PROD_ID = ORDEITEMS.PROD_ID
    JOIN ORDERS AS  ORDERITEMS.ORDER_NUM = ORDERS.ORDER_NUM
    JOIN CUSTOMERS AS ORDERS.CUST_ID = CUSTOMERS.CUST_ID
    WHERE PROD_NAME != prod;
  ELSE
    DBMS_OUTPUT.PUTLINE('Exepthion!!!!');
  END IF;
END
/*3 завдання*/

