-- LABORATORY WORK 4
-- BY Kanievskyi_Vladyslav
DECLARE
NAME_USER WINDOWS.NAME_USER_C%TYPE;
WINDOWS_NAME COMPUTER.WINDOWS_C%TYPE;
CURSOR POSHUK(NAME_OF_PROGRAM PROGRAMS.NAME_PR%TYPE)
IS
SELECT WINDOWS.NAME_USER_C,COMPUTER.WINDOWS_C
FROM WINDOWS LEFT JOIN COMPUTER
ON COMPUTER.WINDOWS_C=WINDOWS.WINDOWS_C
JOIN PROGRAMS
ON PROGRAMS.NAME_PR=COMPUTER.PROGRAMS_C
WHERE PROGRAMS.NAME_PR=NAME_OF_PROGRAM;
BEGIN
OPEN POSHUK('Adobe');
    LOOP
    FETCH POSHUK INTO WINDOWS_NAME,NAME_USER;
        IF (POSHUK %FOUND) THEN
                DBMS_OUTPUT.put_line(NAME_USER || WINDOWS_NAME);  
        ELSE    
            EXIT;
        END IF;    
    END LOOP;
CLOSE  POSHUK;       
END;



create or replace TRIGGER E_dal
    AFTER UPDATE OF email ON Users
    FOR EACH ROW
DECLARE
BEGIN
    DELETE FROM COMPUTER
    where EXISTS
        (SELECT COMPUTER.PROGRAMS_C
        FROM USERS JOIN WINDOWS
            ON (WINDOWS.NAME_USER_C=USERS.NAME AND WINDOWS.PASSWORD_USER_C=USERS.PASSWORD)
        LEFT  JOIN COMPUTER
            ON COMPUTER.WINDOWS_C=WINDOWS.WINDOWS_C
        WHERE USERS.NAME=:new.EMAIL);
END E_dal;

create or replace TRIGGER ver_up
    AFTER UPDATE OF VERSION ON WINDOWS
    FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO PROGRAMS (NAME_PR,PURPOSE,YEAR_OF_ISSUE,VERSION_PR) VALUES('SQL','SQLING','09.06.18','sqlsql');
    DBMS_OUTPUT.put_line('COOL!');
END ver_up;
