-- LABORATORY WORK 5
-- BY Kanievskyi_Vladyslav
CREATE FUNCTION COUNNN(name PRODUCTS.PROD_NAME%TYPE)
RETURN int
as 
coun int;
BEGIN
    SELECT COUNT(VEND_ID) INTO coun
    FROM PRODUCTS 
    WHERE PROD_NAME = name;
    RETURN coun;
    
END;


CREATE OR REPLACE PROCEDURE RENAMEE(ID IN CUSTOMERS.CUST_NAME%TYPE,NEW1 IN CUSTOMERS.CUST_NAME%TYPE)
is 
coun int ;
z exception;
BEGIN
    SELECT COUNT(ORDER_NUM) INTO coun
    FROM ORDERS LEFT JOIN CUSTOMERS
    ON ORDERS.CUST_ID = CUSTOMERS.CUST_ID
    WHERE ID=CUSTOMERS.CUST_ID;
    IF (coun<=0) THEN z;
    ELSE 
    UPDATE VENDORS
    SET CUSTOMERS.CUST_ID=NEW1;
    END IF;
END ;   

CREATE OR REPLACE PROCEDURE GANGE(PRODS_NAME IN PRODUCTS.PROD_NAME%TYPE,
ID1 IN VENDORS.VEND_ID%TYPE,
NAME_NEW IN PRODUCTS.PROD_NAME%TYPE,
ID_NEW IN PRODUCTS.PROD_ID%TYPE,
PRICE_NEW IN PRODUCTS.PROD_PRICE%TYPE,
DESK_NEW IN PRODUCTS.PROD_DESK%TYPE)
is
z exception;
BEGIN
 SELECT VENDORS.VEND_ID,PRODUCTS.PROD_NAME INTO PRODS_NAME,ID
 FROM PRODUCTS LEFT JOIN VENDORS
 WHERE ID1=VENDORS.VEND_ID
 AND
 PRODS_NAME=PRODUCTS.PROD_NAME;
 IF (ID1 IS NULL) OR NEW1=PRODS_NAME THEN z
 ELSE 
 INSERT INTO PRODUCTS VALUES(ID_NEW,ID1,NAME_NEW,PRICE_NEW,DESK_NEW);
 END IF;
 END;
 
