1)
DECLARE
ORDER_DATA1 ORDERS.ORDER_DATA%TYPE ;
CUST_ID VARCHAR2(10):='';
NEW_ORDER_DATA ORDERS.ORDER_DATA%TYPE:='';
ORDER_NUM VARCHAR2(6):='';
BEGIN
SELECT ORDERS.ORDER_DATA INTO ORDER_DATA1
FROM ORDERS
WHERE ORDERS.ORDER_NUM=2005;
FOR  i in 1..10
LOOP
 INSERT into ORDERS(CUST_ID,ORDER_NUM,ORDER_DATA) VALUES (ci,ordi,ORDER_DATA1);
 END LOOP;
END;
2)
DECLARE
status VARCHAR2(12):='';
VEND VENDORS.VEND_ID%TYPE;
COUN INT;
BEGIN
SELECT VENDORS.VEND_ID,COUNT(PRODUCTS.PROD_ID) 
FROM VENDORS LEFT JOIN PRODUCTS
ON VENDORS.VEND_ID=PRODUCTS.VEND_ID
GROUP BY VENDORS.VEND_ID
HAVING VENDORS.VEND_ID=VEND;
IF COUN>=10 THEN
status='більше 10';
ELSE
status=COUN;
END IF;
END;

3)
CREATE VIEW OL1 as
SELECT ORDERITEMS.ORDER_NUM,ORDERITEMS.ORDER_ITEM,VENDORS.VEND_NAME
FROM VENDORS LEFT JOIN PRODUCTS
ON VENDORS.VEND_ID=PRODUCTS.VEND_ID
JOIN ORDERITEMS
ON PRODUCTS.PROD_ID=ORDERITEMS.PROD_ID;


SELECT ORDER_NUM,COUNT(ORDER_ITEM)
FROM OL1;
 
SELECT VEND_NAME,ORDER_NUM
FROM OL1;







