-- LABORATORY WORK 2
-- BY Dovhopol_Yaroslav


/*---------------------------------------------------------------------------
1. Вивести ключ постачальника, що продав лише по одному продукту і тільки 3 покупцям.

---------------------------------------------------------------------------*/
--Код відповідь:
--SELECT VENDORS.VEND_ID
--FROM(
  SELECT CUSTOMERS.CUST_ID, ORDERS.ORDER_NUM, ORDERITEMS.PROD_ID, VENDORS.VEND_ID
  FROM CUSTOMERS JOIN ORDERS
    ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
    JOIN ORDERITEMS
    ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
    JOIN PRODUCTS
    ON ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID
    JOIN VENDORS
    ON PRODUCTS.VEND_ID = VENDORS.VEND_ID
--    GROUP BY VENDORS.VEND_ID
;
--)
--HAVING COUNT(DISTINCT)



/*---------------------------------------------------------------------------
2.  Вивести ключ покупця, замовлення якого не найдорожче.

---------------------------------------------------------------------------*/

--Код відповідь:


--SELECT CUSTOMERS.CUST_ID, SUM(ORDERITEMS.QUANTITY * ORDERITEMS.ITEM_PRICE)
--  FROM CUSTOMERS JOIN ORDERS
--  ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
--  JOIN ORDERITEMS
--  ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
--  GROUP BY CUSTOMERS.CUST_ID
--  HAVING SUM(ORDERITEMS.QUANTITY * ORDERITEMS.ITEM_PRICE) NOT IN (SELECT MAX(ORDERITEMS.QUANTITY * ORDERITEMS.ITEM_PRICE) FROM ORDERITEMS);
--

SELECT CUSTOMERS.CUST_ID
FROM CUSTOMERS JOIN ORDERS
  ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
  JOIN ORDERITEMS
  ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
  GROUP BY CUSTOMERS.CUST_ID
HAVING (SUM(ORDERITEMS.QUANTITY * ORDERITEMS.ITEM_PRICE)) NOT IN(
  SELECT MAX(TOTAL_PRICE)
  FROM(
  SELECT CUSTOMERS.CUST_ID, SUM(ORDERITEMS.QUANTITY * ORDERITEMS.ITEM_PRICE) AS TOTAL_PRICE
    FROM CUSTOMERS JOIN ORDERS
    ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
    JOIN ORDERITEMS
    ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
    GROUP BY CUSTOMERS.CUST_ID)
    );
