-- LABORATORY WORK 3
-- BY Kolesnyk_Mariia
-- 1.
CREATE VIEW orderinfo AS
SELECT ORDERS.ORDER_DATE,
    SUM(ORDERITEMS.QUANTITY*ORDERITEMS.ITEM_PRICE) AS ORDERSUM
    FROM ORDERS 
    JOIN ORDERITEMS ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
    JOIN PRODUCTS ON ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID
GROUP BY ORDERS.ORDER_DATE 
HAVING COUNT(PRODUCTS.PROD_ID)>3;



-- 2.
SELECT INFO.VENDOR_ID, MIN(INFO.COUNT_CUST_ID)
(SELECT VENDORS.VEND_ID AS 'VENDOR_ID',
COUNT(CUSTOMERS.CUST_ID) AS 'COUNT_CUST_ID'
FROM CUSTOMERS 
JOIN ORDERS ON CUSTOMERS.CUST_ID = ORDERS.CUST_ID
JOIN ORDERITEMS ON ORDERS.ORDER_NUM = ORDERITEMS.ORDER_NUM
JOIN PRODUCTS ON ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID
JOIN VENDORS ON PRODUCTS.VEND_ID = VENDORS.VEND_ID
GROUP BY VENDORS.VEND_ID
ORDER BY VENDORS.VEND_ID) INFO GROUP BY INFO.VENDOR_ID;
    
