-- LABORATORY WORK 5
-- BY Kolesnyk_Mariia
--1.
CREATE FUNCTION COUNT_PRODUCT(VEND_NAME_ID IN VARCHAR2)
RETURN NUMBER
IS
COUNT_ORDER_NUMBER NUMBER;
BEGIN
SELECT COUNT(PROD_ID) FROM ORDERITEMS
JOIN VENDORS ON VENDORS.VEND_ID=PRODUCTS.PROD_ID
JOIN PRODUCTS ON PRODUCTS.PROD_ID=ORDERITEMS.ORDER_NUM
WHERE VENDORS.VEND_ID=PROD_ID;
RETURN COUNT_ORDER_NUMBER;
END;


--2.
CREATE PROCEDURE GET_VENDORS_NAME_BY_ID(VENDOR_NAME IN VARCHAR2; VENDOR_ID OUT VARCHAR2);
IS
BEGIN
SELECT VEND_ID INTO VENDOR_ID FROM VENDORS;
WHERE VEND_NAME=VENDOR_NAME;
IF VEND_ID=' ' THEN
RAISE_APPLICATION_ERROR('EXCEPTION');
END IF;
END;


--3.
CREATE PROCEDURE UPDATE_ORDER_DATE
